### ISSUE TITLE
How does i reset the purchases for debug testing ?

### ISSUE THREAD

**Issue by linked67** [MugunthKumar/MKStoreKit#216]
I have found a old code:
[[MKStoreManager sharedManager] removeAllKeychainData];

But it's no more in the latest version and can't find something similar.
It's for testing, how does i clear everyting to start like a new user after i have make some purchase ???

**Comment by MugunthKumar** [comment]
Because of the way App Store stores receipts and because of the way the new MKStoreKit is implemented, we don't store the purchase records in keychain anymore.

So just delete and re-install the app to have a clean slate.

For subscriptions, since they are restored from iTunes, you will have to create a new account every time you want to start with a clean slate. I don't think there is any other way. I might be wrong.
